### ISSUE TITLE
import pythonwhois results in lots of errors

### ISSUE THREAD

**Issue by wilsonchua** [n1cfury/domain-reputation#2]
error: bad escape \s at position 0

G:\anaconda\envs\Python-3-8\lib\sre_parse.py in parse_template(source, state)
   1040                 except KeyError:
   1041                     if c in ASCIILETTERS:
-> 1042                         raise s.error('bad escape %s' % this, len(this))
   1043                 lappend(this)
   1044         else:

**Comment by n1cfury** [comment]
Thanks! Aside from this being made in Python2, I also noticed the site has been changed to Cisco Talos (from senderbase). I will revisit this when I make a new one.
